Add manual coverage checking for _process_auth()
nedsko/httpie pull request #12
Opened 2018-02-26 13:00 UTC by jberglinds

2018-02-26 13:28 UTC, robban112 submitted a review, later dismissed

2018-02-26 15:11 UTC, jojbak commented
Needs multiple if-statements instead of and/or, will patch this.

2018-02-26 16:24 UTC, jojbak commented
Don't merge the patch, needs some fixes.

2018-02-27 08:48 UTC, jberglinds commented
The branch identifiers are way off. 
The code duplication makes this really hard to read, but if you think it's necessary, sure.

2018-02-27 09:21 UTC, jojbak commented
@jberglinds Fixed, the code duplication is quite confusing yes but it works so I suggest we leave like that for now, we can always fix it when everything else is done.

2018-02-27 09:35 UTC, ghost requested changes
Looks much cleaner now, just one minor thing

2018-02-27 09:35 UTC, jojbak commented on httpie/input.py
>              if plugin.auth_require and self.args.auth is None:
The "and self.args.auth is None" statement should be removed, since it has a separate if-statement below.

2018-02-27 09:39 UTC, ghost approved these changes

2018-02-27 09:42 UTC, merged