get_lexer manual coverage
nedsko/httpie pull request #15
Opened 2018-02-26 13:18 UTC by nedsko

2018-02-26 13:21 UTC, jberglinds requested changes
Minor thing, good otherwise

2018-02-26 13:21 UTC, jberglinds commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
This if should have a check right?

2018-02-26 13:30 UTC, robban112 approved these changes

2018-02-26 13:48 UTC, nedsko commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
What sort of check are you referring too? I check if the separate conditions are true below, on line 141.

2018-02-26 16:21 UTC, nedsko commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
Nevermind now I get what you mean 😅

2018-02-26 19:05 UTC, ghost submitted a review, later dismissed
Needs to split up if-statement looks good otherwise

2018-02-26 19:05 UTC, jojbak commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
The if-statement should be split up

2018-02-27 09:10 UTC, jberglinds commented on httpie/output/formatters/colors.py
> +            if isinstance(lexer, TextLexer):
I think this one should be an `elif`

2018-02-27 09:10 UTC, jberglinds commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
It's checked below which branch was actually taken.

2018-02-27 10:01 UTC, jojbak commented on httpie/output/formatters/colors.py
>      if explicit_json and body and (not lexer or isinstance(lexer, TextLexer)):
I see, nvm then

2018-02-27 10:03 UTC, jojbak commented on httpie/output/formatters/colors.py
> +            if isinstance(lexer, TextLexer):
I agree, can fix it

2018-02-27 10:08 UTC, jberglinds approved these changes

2018-02-27 11:06 UTC, merged